### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by ziyaointl** [iamyy/wechat-spider#1]
module.js:471
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Ziyao/Downloads/wechat-spider-master/lib/spider.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by iamyy** [comment]
@ziyaointl Thank you for your feedback. I just fixed this issue by updating file package.json.
